### ISSUE TITLE
non-breaking spaces in room locations

### ISSUE THREAD

**Issue by ericrbg** [goodyguts/durham_calendar#2]
Some modules, for example maths modules, feature non-breaking spaces in the Location info: ![image](https://user-images.githubusercontent.com/37984851/107651629-9f08e380-6c77-11eb-83d7-fa8d7856755e.png)

It'd be nice if it could automatically strip them so GCal doesn't freak out

**Comment by goodyguts** [comment]
Fixed! Sorry it took a bit, summative season and all that...

No commit to report as the fix was on code not in the github repo (it's in my ugly ass web scraping code).
